# -*- coding: utf-8 -*-
"""RAG_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAmphriDq_K8U-jSm6TOAKIJTw3gNfXR
"""

from google.colab import drive
drive.mount('/content/drive')

# ===============================
# STEP 0: Install dependencies
# ===============================
!pip install -q langchain langchain-community sentence-transformers faiss-cpu pypdf transformers accelerate torch

# ===============================
# STEP 1: Import libraries
# ===============================
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
from langchain.llms import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

# ===============================
# STEP 2: Load PDF and split text
# ===============================
pdf_path = "/content/drive/MyDrive/AI/train_your_bot.pdf"  # <-- Your PDF about proofreading
loader = PyPDFLoader(pdf_path)
documents = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
docs = text_splitter.split_documents(documents)

# Clean text (remove extra newlines)
for doc in docs:
    doc.page_content = doc.page_content.replace("\n", " ").strip()

print(f"Total chunks: {len(docs)}")

# ===============================
# STEP 3: Create embeddings and vector store
# ===============================
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vectorstore = FAISS.from_documents(docs, embedding_model)

# ===============================
# STEP 4: Load local LLM (Falcon 7B instruct)
# ===============================
model_name = "tiiuae/falcon-7b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype="auto")

pipe = pipeline(
    task="text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    temperature=0.7
)
llm = HuggingFacePipeline(pipeline=pipe)

# ===============================
# STEP 5: Create a custom prompt
# ===============================
qa_prompt = PromptTemplate(
    template="""You are an assistant that answers questions based ONLY on the given context.
Do not add extra filler text. Answer in clear, simple sentences.

Context:
{context}

Question: {question}

Answer:""",
    input_variables=["context", "question"],
)

# ===============================
# STEP 6: Setup RetrievalQA (RAG)
# ===============================
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vectorstore.as_retriever(search_kwargs={"k": 3}),
    chain_type="stuff",
    chain_type_kwargs={"prompt": qa_prompt}
)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vectorstore.as_retriever(search_kwargs={"k": 3}),
    chain_type="stuff",
    chain_type_kwargs={"prompt": qa_prompt},
    return_source_documents=True   # 👈 this makes "source_documents" available
)
result = qa_chain.invoke({"query": query})

# Main Concept
query = "What is the main concept of proofreading according to this PDF?"
result = qa_chain.invoke({"query": query})
print("Answer:\n", result["result"])
print("\nSources:")
for i, doc in enumerate(result["source_documents"], 1):
    print(f"--- Source {i} ---")
    print(doc.page_content[:300], "...\n")   # print first 300 chars for readability

# ===============================
# STEP 7: Ask Questions (with Sources)
# ===============================

# --- Summary ---
summary_query = "Summarize the key points of this PDF on proofreading in 5 bullet points."
result = qa_chain.invoke({"query": summary_query})
print("\nSummary:\n", result["result"])

print("\nSummary Sources:")
for i, doc in enumerate(result["source_documents"], 1):
    print(f"--- Source {i} ---\n{doc.page_content[:300]}...\n")  # first 300 chars

# --- Summary ---
summary_query = "Summarize the key points of this PDF on History of Intrusion Detection in 5 bullet points."
result = qa_chain.invoke({"query": summary_query})
print("\nSummary:\n", result["result"])

print("\nSummary Sources:")
for i, doc in enumerate(result["source_documents"], 1):
    print(f"--- Source {i} ---\n{doc.page_content[:300]}...\n")  # first 300 chars

# ===============================
# STEP 7: Generate MCQs with Sources
# ===============================

# Define MCQ query
mcq_query = """
Based ONLY on the context from the PDF, generate 5 multiple-choice questions
about the *History of Intrusion Detection*.
Each must have 4 options (A–D) and clearly show the correct answer.

If the PDF does not have enough information to answer, reply:
"Not enough information in the PDF."
"""

# Run QA chain
result = qa_chain.invoke({"query": mcq_query})

# Print MCQs
print("\nMCQs:\n", result["result"])

# Print Sources
print("\nMCQ Sources:")
for i, doc in enumerate(result["source_documents"], 1):
    print(f"--- Source {i} ---")
    print(doc.page_content[:300], "...\n")  # show first 300 chars for readability

